log:
  level: debug
  disable_sentry: true

db:
  url: postgres://points:points@rarime-points-db:5432/points?sslmode=disable

listener:
  addr: :80

event_types:
  types:
    - name: get_poh
      title: Get PoH credential
      reward: 50
      description: Prove that you are human
      frequency: one-time
    - name: free_weekly
      title: Free weekly points
      reward: 100
      frequency: weekly
      description: |
        ## Free Weekly Points
        
        This is markdown sample.
        
        ### How it works
        
        - Users are eligible to participate once every week.
        - Upon participation, users will receive 100 points.
        - These points can be used for various features in the application.
    - name: daily_login
      title: Daily login
      reward: 5
      frequency: daily
      description: Login every day
      disabled: true
    - name: be_referred
      title: Referral welcome bonus
      reward: 5
      frequency: one-time
      description: Be referred by a friend and get a welcome bonus
      no_auto_open: true
    - name: referral_common
      title: Refer new users
      reward: 25
      frequency: one-time
      description: Refer friends and get a reward for each friend who verifies the passport
      disabled: true
    - name: referral_specific
      title: Refer user {:did}
      reward: 25
      frequency: unlimited
      description: The user {:did} has verified the passport. Claim the reward!
      no_auto_open: true
      disabled: true

auth:
  addr: http://rarime-auth

broadcaster:
  addr: "http://broadcaster"
  sender_account: "rarimo15hcd6tv7pe8hk2re7hu0zg0aphqdm2dtjrs0ds"

withdrawal:
  point_price_urmo: 100

sbt_check:
  networks:
    - name: polygon
      disabled: true
      rpc: https://your-rpc
      contract: 0x7DdAde70efADf832A600ba483FAD26fCA477FE2A
      request_timeout: 5s
      start_from_block: 48984542
      block_window: 3
      max_blocks_per_request: 5000
    - name: ethereum
      disabled: true
      rpc: https://your-rpc
      contract: 0x...
      request_timeout: 5s

