log:
  disable_sentry: true
  level: debug

listener:
  addr: :80

issuer:
  base_url: http://issuer-api
  auth_username: "user"
  auth_password: "password"

orgs:
  verify_domain: false

db:
  url: postgres://orgs:orgs@rarime-orgs-db:5432/orgs?sslmode=disable

notificator:
  app_base_url: https://app.rarime.com
  api_key: "" # https://mailchimp.com/developer/transactional/guides/quick-start/#generate-your-api-key

aws:
  disabled: false
  access_key: miniominio
  secret_key: sekritsekrit
  region: us-east-1
  endpoint: storage:9000
  disable_ssl: true

s3:
  bucket: "orgs"
  ensure_bucket: true
  client_url: http://storage:9000/orgs
  media_types:
    logo:
      - image/jpeg
      - image/png
      - image/gif

auth:
  addr: auth-svc:80